version: '3'

services:
  frontend:
    build:
      dockerfile: deployment/docker/Dockerfile.frontend
      context: .
      args:
        NODE_PORT: ${NODE_PORT-8080}
    volumes:
      - .:/var/www/

  nginx:
    build:
      dockerfile: deployment/docker/Dockerfile.nginx
      context: .
    ports:
      - 80:80 
      - 443:443 
    depends_on:
      - frontend
    links:
      - frontend
    volumes:
      - .:/var/www/
